export type Evidence = { label: string; value: string }

export type Stage = {
  n: string
  phase: string
  name: string
  desc: string
  does: string[]
  input: string
  output: string
  artifact: string
  evidence: Evidence[]
}

export const stages: Stage[] = [
  {
    n: '01',
    phase: 'Understand',
    name: 'Environment Precheck',
    desc: 'Resolve the environment before the investigation begins.',
    does: ['repository', 'environment', 'sandbox'],
    input: 'Repository',
    output: 'Reproducible environment',
    artifact: 'Environment',
    evidence: [
      { label: 'runtime', value: 'python 3.11.9' },
      { label: 'framework', value: 'fastapi' },
      { label: 'test runner', value: 'pytest' },
      { label: 'dependencies', value: '47 resolved' },
      { label: 'confidence', value: '0.96' },
    ],
  },
  {
    n: '02',
    phase: 'Understand',
    name: 'Repository Indexing',
    desc: 'Decompose the repository into files, modules and entrypoints.',
    does: ['environment', 'file tree', 'symbol index'],
    input: 'Reproducible environment',
    output: 'Repository index',
    artifact: 'Repository Model',
    evidence: [
      { label: 'files', value: '42 indexed' },
      { label: 'modules', value: '18' },
      { label: 'entrypoints', value: '7' },
      { label: 'relationships', value: '31' },
    ],
  },
  {
    n: '03',
    phase: 'Understand',
    name: 'Repository Intelligence',
    desc: 'Recover what the code means, not just what it contains.',
    does: ['symbols', 'behaviour', 'intent'],
    input: 'Repository index',
    output: 'Semantic model',
    artifact: 'Semantic Model',
    evidence: [
      { label: 'functions understood', value: '312' },
      { label: 'contracts inferred', value: '24' },
      { label: 'ambiguous', value: '3' },
      { label: 'confidence', value: '0.88' },
    ],
  },
  {
    n: '04',
    phase: 'Understand',
    name: 'Dependency Analyzer',
    desc: 'Trace what changes when the suspected function changes.',
    does: ['semantic model', 'edges', 'propagation'],
    input: 'Semantic model',
    output: 'Dependency graph',
    artifact: 'Dependency Graph',
    evidence: [
      { label: 'internal edges', value: '128' },
      { label: 'external packages', value: '47' },
      { label: 'cycles', value: '0' },
      { label: 'critical paths', value: '4' },
    ],
  },
  {
    n: '05',
    phase: 'Understand',
    name: 'Static Analysis',
    desc: 'Pin defects to exact source locations, ranked by severity.',
    does: ['source', 'findings', 'severity'],
    input: 'Dependency graph',
    output: 'Static findings',
    artifact: 'Static Findings',
    evidence: [
      { label: 'findings', value: '3' },
      { label: 'high', value: '1' },
      { label: 'medium', value: '1' },
      { label: 'low', value: '1' },
    ],
  },
  {
    n: '06',
    phase: 'Prove',
    name: 'Failure Reproduction',
    desc: 'Can the reported failure actually be reproduced?',
    does: ['sandbox', 'execution trace', 'failure'],
    input: 'Static findings',
    output: 'Reproduced failure',
    artifact: 'Reproduced Failure',
    evidence: [
      { label: 'runs', value: '3 / 3 failed' },
      { label: 'deterministic', value: 'yes' },
      { label: 'failing test', value: 'test_auth.py:41' },
      { label: 'status', value: 'reproducible' },
    ],
  },
  {
    n: '07',
    phase: 'Prove',
    name: 'Root Cause Analysis',
    desc: 'Find the smallest explanation that accounts for the failure.',
    does: ['evidence', 'convergence', 'cause'],
    input: 'Reproduced failure',
    output: 'Root cause',
    artifact: 'Root Cause',
    evidence: [
      { label: 'location', value: 'app/cache.py:34' },
      { label: 'evidence sources', value: '4' },
      { label: 'alternatives ruled out', value: '5' },
      { label: 'confidence', value: '0.91' },
    ],
  },
  {
    n: '08',
    phase: 'Prove',
    name: 'Blast Radius',
    desc: 'Measure everything the repair can reach.',
    does: ['cause', 'callers', 'runtime paths'],
    input: 'Root cause',
    output: 'Impact surface',
    artifact: 'Blast Radius',
    evidence: [
      { label: 'reachable functions', value: '12' },
      { label: 'runtime paths', value: '4' },
      { label: 'untested paths', value: '2' },
      { label: 'high-risk boundary', value: '1' },
    ],
  },
  {
    n: '09',
    phase: 'Repair',
    name: 'Context Engineering',
    desc: 'Select only the evidence-relevant context. Discard the rest.',
    does: ['247 files', 'filters', '7 files'],
    input: 'Impact surface',
    output: 'Repair context',
    artifact: 'Repair Context',
    evidence: [
      { label: 'files', value: '247 → 7' },
      { label: 'functions', value: '3' },
      { label: 'tests', value: '2' },
      { label: 'contracts', value: '1' },
    ],
  },
  {
    n: '10',
    phase: 'Repair',
    name: 'Repair Planner',
    desc: 'Order the repair so every edit lands with its prerequisites met.',
    does: ['context', 'ordered DAG', 'plan'],
    input: 'Repair context',
    output: 'Repair plan',
    artifact: 'Repair Plan',
    evidence: [
      { label: 'steps', value: '4' },
      { label: 'blocked until', value: 'contract update' },
      { label: 'invariants preserved', value: '2' },
      { label: 'risk', value: 'low' },
    ],
  },
  {
    n: '11',
    phase: 'Repair',
    name: 'Patch Generator',
    desc: 'Emit the fewest lines that resolve the proven root cause.',
    does: ['plan', 'transformation', 'diff'],
    input: 'Repair plan',
    output: 'Patch',
    artifact: 'Patch',
    evidence: [
      { label: 'files touched', value: '2' },
      { label: 'lines added', value: '+3' },
      { label: 'lines removed', value: '−1' },
      { label: 'behaviour changed', value: 'guarded path only' },
    ],
  },
  {
    n: '12',
    phase: 'Validate',
    name: 'Mutation Validation',
    desc: 'Do the tests actually detect the defect, or just pass?',
    does: ['patch', 'mutants', 'kill rate'],
    input: 'Patch',
    output: 'Validation result',
    artifact: 'Validation',
    evidence: [
      { label: 'suite', value: '48 / 48 pass' },
      { label: 'mutants killed', value: '19 / 21' },
      { label: 'survived', value: '2' },
      { label: 'MCI', value: '0.82' },
    ],
  },
  {
    n: '13',
    phase: 'Validate',
    name: 'Security Re-scan',
    desc: 'Compare the security surface before and after the patch.',
    does: ['before', 'delta', 'after'],
    input: 'Validation result',
    output: 'Security delta',
    artifact: 'Security Delta',
    evidence: [
      { label: 'before', value: '3 findings' },
      { label: 'after', value: '2 findings' },
      { label: 'new findings', value: '0' },
      { label: 'secrets scan', value: 'clean' },
    ],
  },
  {
    n: '14',
    phase: 'Validate',
    name: 'Mergeability Assessment',
    desc: 'Weigh every signal into one honest decision.',
    does: ['evidence', 'gates', 'decision'],
    input: 'Security delta',
    output: 'Merge decision',
    artifact: 'Merge Decision',
    evidence: [
      { label: 'gates passed', value: '7 / 7' },
      { label: 'confidence', value: '0.91' },
      { label: 'decision', value: 'proven fix' },
      { label: 'state', value: 'ready for review' },
    ],
  },
]

